[package]
name = "tide_bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tide_server"
path = "tide.rs"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
serde = "1.0.140"
serde_json = "1.0.82"
tide = "0.16.0"
