#!/usr/bin/env bash

if [ -z $WORKERS ]; then
	export WORKERS=1
fi
if [ -z $THREADS ]; then
  export THREADS=10
fi

SCRIPT_DIR=$(realpath -s $(dirname ${BASH_SOURCE[0]}))
export PYTHONPATH=$SCRIPT_DIR

gunicorn -w $WORKERS -k gthread --threads $THREADS -b 0.0.0.0:1729 "flask_server:create_app()"
