[package]
name = "axum_bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "axum_server"
path = "axum.rs"

[dependencies]
axum = "0.5.13"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["full"] }
